FROM --platform=linux/amd64 python:3.12-slim as build

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy only the requirements file first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose port 8080 for the Flask app
EXPOSE 8080

# Command to run the app
CMD ["python", "app.py"]


#docker build -t jsonlee242/youtubedownloader:latest .
#docker push jsonlee242/youtubedownloader:latest